name: Node.js CI

on: [push]

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
            key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
            path: |
              ./node_modules
      - run: npm install

  lint:
    needs: dependencies

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - run: npm run lint

  build:
    needs: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - run: |
          echo ${{ github.event.repository.name }}
          BASE_URL=/${{ github.event.repository.name }} npm run build
      - name: Archive artufacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: build
    uses: polinamamchur/GPA_Calculator/react-examples/.github/workflows/static.yml@main



  sun-subflow:
    uses: polinamamchur/GPA_Calculator/.github/workflows/reusable.yml@main
    with:
      some: 'some-parameter-here'