name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
      - run: npm install

  lint:
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
      - run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
      - run: |
          echo ${{ github.event.repository.name }}
          BASE_URL=/${{ github.event.repository.name }} npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish

  sun-subflow:
    runs-on: ubuntu-latest
    needs: dependencies

    steps:
      - name: Run Subflow
        uses: polinamamchur/GPA_Calculator/.github/workflows/reusable.yml@main
        with:
          some: 'some-parameter-here'
